-- H2 本地文件数据库初始化脚本。
-- icecore-1：极地冰芯样本库与冻融环境监测闭环
-- icecore-2：多租户数据权限、分钟级库温事件、层位切片与运营检索增强

CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

-- ============================================================
-- icecore-1：极地冰芯样本库与冻融环境监测闭环
-- 钻取任务 / 库位 / 样本盒 / 冰芯样本 / 分析批次 / 批次明细
-- 关键业务键均建唯一约束；审计列由 MyBatis-Plus 自动填充
-- icecore-2：业务对象增加 tenant_id 列（0 表示平台/历史数据）
-- ============================================================

-- 钻取任务
CREATE TABLE IF NOT EXISTS t_drill_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR(32) NOT NULL,
    task_name VARCHAR(128) NOT NULL,
    site_name VARCHAR(128) NOT NULL,
    drill_depth DECIMAL(10,2),
    status VARCHAR(16) NOT NULL DEFAULT 'PLANNED',
    planned_start DATE,
    planned_end DATE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_drill_task_no UNIQUE (task_no)
);

-- 冻库库位（layer_no 即冰芯层位分区键）
CREATE TABLE IF NOT EXISTS t_storage_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_code VARCHAR(32) NOT NULL,
    warehouse VARCHAR(64) NOT NULL,
    shelf_no VARCHAR(32),
    layer_no VARCHAR(32),
    set_temperature DECIMAL(5,2),
    capacity INT NOT NULL DEFAULT 1,
    status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    tenant_id BIGINT NOT NULL DEFAULT 0,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_storage_location_code UNIQUE (location_code)
);

-- 样本盒
CREATE TABLE IF NOT EXISTS t_sample_box (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    box_no VARCHAR(32) NOT NULL,
    task_id BIGINT NOT NULL,
    location_id BIGINT,
    capacity INT NOT NULL DEFAULT 20,
    status VARCHAR(16) NOT NULL DEFAULT 'EMPTY',
    sealed_time TIMESTAMP,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_sample_box_no UNIQUE (box_no)
);

-- 冰芯样本（层位、温度、融水量、取样完整度）
CREATE TABLE IF NOT EXISTS t_ice_core_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_no VARCHAR(32) NOT NULL,
    task_id BIGINT NOT NULL,
    box_id BIGINT NOT NULL,
    location_id BIGINT,
    layer_no VARCHAR(32) NOT NULL,
    depth_top DECIMAL(10,2),
    depth_bottom DECIMAL(10,2),
    temperature DECIMAL(5,2),
    melt_water_ml DECIMAL(10,2),
    integrity_pct DECIMAL(5,2),
    status VARCHAR(16) NOT NULL DEFAULT 'STORED',
    sampled_at TIMESTAMP,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_ice_core_sample_no UNIQUE (sample_no)
);

-- 分析批次（实验室对象，可跨租户分析样本，按对象授权控制可见性）
CREATE TABLE IF NOT EXISTS t_analysis_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no VARCHAR(32) NOT NULL,
    batch_name VARCHAR(128) NOT NULL,
    analysis_type VARCHAR(64),
    status VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    accepted_time TIMESTAMP,
    posted_time TIMESTAMP,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_analysis_batch_no UNIQUE (batch_no)
);

-- 分析批次明细（批次与样本关联，同一样本在同一批次内唯一）
CREATE TABLE IF NOT EXISTS t_analysis_batch_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_batch_item_sample UNIQUE (batch_id, sample_id)
);

-- ============================================================
-- icecore-2：多租户账号与对象级数据授权
-- ============================================================

-- 租户
CREATE TABLE IF NOT EXISTS t_sys_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(32) NOT NULL,
    tenant_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_sys_tenant_code UNIQUE (tenant_code)
);

-- 账号：role 取 PLATFORM / TENANT_ADMIN / TENANT_USER
--   PLATFORM      平台运营，可见全部对象，不受租户限制
--   TENANT_ADMIN  租户管理员，可见本租户全部对象
--   TENANT_USER   租户成员，仅见 t_data_grant 显式授权对象
CREATE TABLE IF NOT EXISTS t_sys_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    tenant_id BIGINT,
    role_code VARCHAR(32) NOT NULL DEFAULT 'TENANT_USER',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_sys_account_username UNIQUE (username)
);

-- 对象级授权：object_type 取 TASK / LOCATION / BOX / SAMPLE / BATCH
CREATE TABLE IF NOT EXISTS t_data_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    object_type VARCHAR(16) NOT NULL,
    object_id BIGINT NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_data_grant UNIQUE (account_id, object_type, object_id)
);

-- ============================================================
-- icecore-2：冻融环境监测 —— 分钟级库温事件（压测量级 100,000+）
-- ============================================================
CREATE TABLE IF NOT EXISTS t_freezer_temperature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    recorded_at TIMESTAMP NOT NULL,
    measured_temperature DECIMAL(6,2) NOT NULL,
    set_temperature DECIMAL(6,2),
    deviation DECIMAL(6,2),
    alarm_flag INT NOT NULL DEFAULT 0,
    create_time TIMESTAMP
);

-- ============================================================
-- icecore-2：冰芯层位切片（压测量级 500,000+）
-- 每个样本按深度切出多个分钟级层位切片，layer_no 为分区键
-- ============================================================
CREATE TABLE IF NOT EXISTS t_ice_layer_slice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id BIGINT NOT NULL,
    location_id BIGINT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    layer_no VARCHAR(32) NOT NULL,
    slice_index INT NOT NULL,
    depth_top DECIMAL(10,2),
    depth_bottom DECIMAL(10,2),
    temperature DECIMAL(6,2),
    measured_at TIMESTAMP,
    create_time TIMESTAMP,
    CONSTRAINT uk_layer_slice UNIQUE (sample_id, slice_index)
);

-- ============================================================
-- 检索/压测索引：外键维度、状态/层位分区、时间范围、租户权限
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_task_tenant       ON t_drill_task (tenant_id, id);
CREATE INDEX IF NOT EXISTS idx_task_status       ON t_drill_task (status, id);
CREATE INDEX IF NOT EXISTS idx_loc_tenant_layer  ON t_storage_location (tenant_id, layer_no, id);
CREATE INDEX IF NOT EXISTS idx_loc_layer         ON t_storage_location (layer_no, id);
CREATE INDEX IF NOT EXISTS idx_box_task          ON t_sample_box (task_id);
CREATE INDEX IF NOT EXISTS idx_box_location      ON t_sample_box (location_id);
CREATE INDEX IF NOT EXISTS idx_box_tenant        ON t_sample_box (tenant_id, id);
CREATE INDEX IF NOT EXISTS idx_smp_task          ON t_ice_core_sample (task_id);
CREATE INDEX IF NOT EXISTS idx_smp_box           ON t_ice_core_sample (box_id);
CREATE INDEX IF NOT EXISTS idx_smp_location      ON t_ice_core_sample (location_id);
CREATE INDEX IF NOT EXISTS idx_smp_status        ON t_ice_core_sample (status, id);
CREATE INDEX IF NOT EXISTS idx_smp_tenant_layer  ON t_ice_core_sample (tenant_id, layer_no, id);
CREATE INDEX IF NOT EXISTS idx_smp_layer         ON t_ice_core_sample (layer_no, id);
CREATE INDEX IF NOT EXISTS idx_smp_sampled_at    ON t_ice_core_sample (sampled_at);
CREATE INDEX IF NOT EXISTS idx_batch_item_batch  ON t_analysis_batch_item (batch_id);
CREATE INDEX IF NOT EXISTS idx_batch_item_sample ON t_analysis_batch_item (sample_id);
CREATE INDEX IF NOT EXISTS idx_grant_account     ON t_data_grant (account_id, object_type, object_id);
CREATE INDEX IF NOT EXISTS idx_grant_tenant      ON t_data_grant (tenant_id, object_type);
CREATE INDEX IF NOT EXISTS idx_temp_loc_time     ON t_freezer_temperature (location_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_temp_time         ON t_freezer_temperature (recorded_at);
CREATE INDEX IF NOT EXISTS idx_temp_alarm        ON t_freezer_temperature (alarm_flag, recorded_at);
CREATE INDEX IF NOT EXISTS idx_temp_tenant       ON t_freezer_temperature (tenant_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_slice_sample      ON t_ice_layer_slice (sample_id, slice_index);
CREATE INDEX IF NOT EXISTS idx_slice_layer       ON t_ice_layer_slice (layer_no, id);
CREATE INDEX IF NOT EXISTS idx_slice_tenant_layer ON t_ice_layer_slice (tenant_id, layer_no, id);
CREATE INDEX IF NOT EXISTS idx_slice_location    ON t_ice_layer_slice (location_id, layer_no, id);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('icecore-1', '极地冰芯样本库与冻融环境监测闭环');

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('icecore-2', '多租户数据权限、分钟级库温与层位切片运营检索增强');
