-- H2 本地文件数据库初始化脚本。F1 在此基础上补充业务表。
CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

-- ============================================================
-- icecore-1：极地冰芯样本库与冻融环境监测闭环
-- 钻取任务 / 库位 / 样本盒 / 冰芯样本 / 分析批次 / 批次明细
-- 关键业务键均建唯一约束；审计列由 MyBatis-Plus 自动填充
-- ============================================================

-- 钻取任务
CREATE TABLE IF NOT EXISTS t_drill_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR(32) NOT NULL,
    task_name VARCHAR(128) NOT NULL,
    site_name VARCHAR(128) NOT NULL,
    drill_depth DECIMAL(10,2),
    status VARCHAR(16) NOT NULL DEFAULT 'PLANNED',
    planned_start DATE,
    planned_end DATE,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_drill_task_no UNIQUE (task_no)
);

-- 冻库库位
CREATE TABLE IF NOT EXISTS t_storage_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_code VARCHAR(32) NOT NULL,
    warehouse VARCHAR(64) NOT NULL,
    shelf_no VARCHAR(32),
    layer_no VARCHAR(32),
    set_temperature DECIMAL(5,2),
    capacity INT NOT NULL DEFAULT 1,
    status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_storage_location_code UNIQUE (location_code)
);

-- 样本盒
CREATE TABLE IF NOT EXISTS t_sample_box (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    box_no VARCHAR(32) NOT NULL,
    task_id BIGINT NOT NULL,
    location_id BIGINT,
    capacity INT NOT NULL DEFAULT 20,
    status VARCHAR(16) NOT NULL DEFAULT 'EMPTY',
    sealed_time TIMESTAMP,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_sample_box_no UNIQUE (box_no)
);

-- 冰芯样本（层位、温度、融水量、取样完整度）
CREATE TABLE IF NOT EXISTS t_ice_core_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_no VARCHAR(32) NOT NULL,
    task_id BIGINT NOT NULL,
    box_id BIGINT NOT NULL,
    location_id BIGINT,
    layer_no VARCHAR(32) NOT NULL,
    depth_top DECIMAL(10,2),
    depth_bottom DECIMAL(10,2),
    temperature DECIMAL(5,2),
    melt_water_ml DECIMAL(10,2),
    integrity_pct DECIMAL(5,2),
    status VARCHAR(16) NOT NULL DEFAULT 'STORED',
    sampled_at TIMESTAMP,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_ice_core_sample_no UNIQUE (sample_no)
);

-- 分析批次
CREATE TABLE IF NOT EXISTS t_analysis_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no VARCHAR(32) NOT NULL,
    batch_name VARCHAR(128) NOT NULL,
    analysis_type VARCHAR(64),
    status VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    accepted_time TIMESTAMP,
    posted_time TIMESTAMP,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_analysis_batch_no UNIQUE (batch_no)
);

-- 分析批次明细（批次与样本关联，同一样本在同一批次内唯一）
CREATE TABLE IF NOT EXISTS t_analysis_batch_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_batch_item_sample UNIQUE (batch_id, sample_id)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('icecore-1', '极地冰芯样本库与冻融环境监测闭环');
